default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  username: <%= ENV['ROBBIE_LANE_DATABASE_USER'] %> 
  password: <%= ENV['ROBBIE_LANE_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: robbie_lane_development

test:
  <<: *default
  database: robbie_lane_test

production:
  <<: *default
  database: robbie_lane_production
  host: localhost
  username: <%= ENV['ROBBIE_LANE_DATABASE_USER'] %> 
  password: <%= ENV['ROBBIE_LANE_DATABASE_PASSWORD'] %>
